name: Build and Publish Reactive Images
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version

      - name: Build Micronaut project
        run: |
          cd reactive/micronaut
          ./gradlew dockerBuildNative
          docker tag app:latest mraible/micronaut-reactive:latest
        shell: bash

      - name: Build Quarkus project
        run: |
          cd reactive/quarkus
          ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
          docker build -f src/main/docker/Dockerfile.native -t quarkus .
          docker tag quarkus:latest mraible/quarkus-reactive:latest
        shell: bash

      - name: Build Spring Boot project
        run: |
          cd reactive/spring-boot
          ./gradlew bootBuildImage --imageName=spring-boot
          docker tag spring-boot:latest mraible/spring-boot-reactive:latest
        shell: bash

      - name: Build Helidon project
        run: |
          cd reactive/helidon
          docker build -t helidon -f Dockerfile.native .
          docker tag helidon:latest mraible/helidon-reactive:latest
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish Micronaut Reactive Docker image to DockerHub
        run: |
          docker push mraible/micronaut-reactive:latest
        shell: bash

      - name: Publish Quarkus Reactive Docker image to DockerHub
        run: |
          docker push mraible/quarkus-reactive:latest
        shell: bash

      - name: Publish Spring Boot WebFlux Docker image to DockerHub
        run: |
          docker push mraible/spring-boot-reactive:latest
        shell: bash

      - name: Publish Helidon SE Docker image to DockerHub
        run: |
          docker push mraible/helidon-reactive:latest
        shell: bash
